---
output:
  pdf_document: default
  html_document: default
---

# Exercise 4 (Problem Set 5)

* Due date: July 8th (Tue) 11pm.
* This is the last problem set!

## Rules

- If you are enrolled in Japanese class (i.e., Wednesday 2nd), you can use both Japanese and English to write your answer. 
- Submit your solution through `CourseN@vi`.
- **Important:** Submission format
  - If you use Rmarkdown, please compile your Rmarkdown file into either "html" or "PDF" file and submit **both** the compiled file and a Rmarkdown file. 
  - If you do not use Rmarkdown, please submit the document file that contains your answer and R script file (.R file) **separately**, that is, you submit **two files**.


## Question 1: Hansford and Gomez (2010, APSR)

- This problem set is based on THOMAS G. HANSFORD and BRAD T. GOMEZ "Estimating the Electoral Effects of Voter Turnout" The American Political Science Review Vol. 104, No. 2 (May 2010), pp. 268-288
    - Link: https://www.cambridge.org/core/journals/american-political-science-review/article/estimating-the-electoral-effects-of-voter-turnout/8A880C28E79BE770A5CA1A9BB6CF933C
- You will use the same dataset as I introduced in the chapter for instrumental variable estimation.

## Questions

1. What is the research question of this paper? Provide a summary up to 2-3 sentences. 
2. What is the difficulty of the analysis?  Provide a summary up to 2-3 sentences.
3. 3.	What is the research design, i.e., how do authors overcome the issue? 
4.	Summarize four hypothesis the authors are trying to test.
5.	Replicate the first three columns of Table A1 to the best of your ability. 
6.	Replicate Table 1 to the best of your ability. 
7.	Interpret the results from Table 1 in terms of those three hypotheses. 

**Note** Do not worry about the standard errors in replication exercise. 